ACARProje.ToDo.Web/Areas/Admin/Models/AciliyetAddViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ACARProje.ToDo.Web.Areas.Admin.Models
{
    public class AciliyetAddViewModel
    {
        [Display(Name = "Tanım")]
        [Required(ErrorMessage = "Tanım alanı boş geçilemez !")]
        public string Tanim { get; set; }
    }
}

ACARProje.ToDo.Web/Areas/Admin/Models/AciliyetListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ACARProje.ToDo.Web.Areas.Admin.Models
{
    public class AciliyetListViewModel
    {
        public int Id { get; set; }
        public string Tanim { get; set; }
    }
}

ACARProje.ToDo.Web/Areas/Admin/Models/AciliyetUpdateViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ACARProje.ToDo.Web.Areas.Admin.Models
{
    public class AciliyetUpdateViewModel
    {
        public int Id { get; set; }
        [Display(Name ="Tanım :")]
        [Required(ErrorMessage =("Tanım alanı gereklidir."))]
        public string Tanim { get; set; }
    }
}

ACARProje.ToDo.Web/Areas/Admin/Models/GorevAddViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ACARProje.ToDo.Web.Areas.Admin.Models
{
    public class GorevAddViewModel
    {
        [Required(ErrorMessage ="Ad alanı gereklidir !")]
        public string Ad { get; set; }

        public string Aciklama { get; set; }
        [Range(0,int.MaxValue,ErrorMessage ="Lütfen bir aciliyet durumu seçiniz !")]
        public int AciliyetId { get; set; }

        public SelectList Aciliyetler { get; set; }
    }
}

ACARProje.ToDo.Web/Areas/Admin/Models/GorevListViewModel.cs
using ACARProje.ToDo.Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ACARProje.ToDo.Web.Areas.Admin.Models
{
    public class GorevListViewModel
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Aciklama { get; set; }
        public bool Durum { get; set; }
        public DateTime OlusturulmaTarih { get; set; }

        public int AciliyetId { get; set; }
        public Aciliyet Aciliyet { get; set; }
    }
}

ACARProje.ToDo.Web/Areas/Admin/Controllers/AciliyetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ACARProje.ToDo.Business.Interfaces;
using ACARProje.ToDo.Entities.Concrete;
using ACARProje.ToDo.Web.Areas.Admin.Models;
using Microsoft.AspNetCore.Mvc;

namespace ACARProje.ToDo.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AciliyetController : Controller
    {
        public readonly IAciliyetService _aciliyetService;
        public AciliyetController(IAciliyetService aciliyetService)
        {
            _aciliyetService = aciliyetService;
        }
        public IActionResult Index()
        {
            TempData["Active"] = "aciliyet";
            List<Aciliyet> aciliyetler = _aciliyetService.GetirHepsi();
            List<AciliyetListViewModel> model = new List<AciliyetListViewModel>();

            foreach (var item in aciliyetler)
            {
                AciliyetListViewModel aciliyetModel = new AciliyetListViewModel();
                aciliyetModel.Id = item.Id;
                aciliyetModel.Tanim = item.Tanim;
                model.Add(aciliyetModel);
            }
            return View(model);
        }

        public IActionResult EkleAciliyet()
        {
            TempData["Active"] = "aciliyet";

            return View(new AciliyetAddViewModel());
        }

        [HttpPost]
        public IActionResult EkleAciliyet(AciliyetAddViewModel model)
        {
            if (ModelState.IsValid)
            {
                _aciliyetService.Kaydet(new Aciliyet()
                {

                    Tanim = model.Tanim
                });
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public IActionResult GuncelleAciliyet(int id)
        {
            TempData["Active"] = "aciliyet";

            var aciliyet = _aciliyetService.GetirIdile(id);
            AciliyetUpdateViewModel model = new AciliyetUpdateViewModel
            {
                Id = aciliyet.Id,
                Tanim = aciliyet.Tanim
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult GuncelleAciliyet(AciliyetUpdateViewModel model)
        {

            if (ModelState.IsValid)
            {
                _aciliyetService.Guncelle(new Aciliyet
                {
                    Id = model.Id,
                    Tanim = model.Tanim

                });
                return RedirectToAction("Index");
            }
         

            return View(model);
        }
    }
}

ACARProje.ToDo.Web/Areas/Admin/Controllers/GorevController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ACARProje.ToDo.Business.Interfaces;
using ACARProje.ToDo.Entities.Concrete;
using ACARProje.ToDo.Web.Areas.Admin.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ACARProje.ToDo.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class GorevController : Controller
    {
        private readonly IGorevService _gorevService;
        private readonly IAciliyetService _aciliyetService;
        public GorevController(IGorevService gorevService, IAciliyetService aciliyetService)
        {
            _gorevService = gorevService;
            _aciliyetService = aciliyetService;
        }
        public IActionResult Index()
        {
            TempData["Active"] = "gorev";

           List<Gorev> gorevler= _gorevService.GetirAciliyetIleTamamlanmayan();
            List<GorevListViewModel> models = new List<GorevListViewModel>();
            foreach (var item in gorevler)
            {
                GorevListViewModel model = new GorevListViewModel
                {
                    Aciklama = item.Aciklama,
                    Aciliyet = item.Aciliyet,
                    AciliyetId = item.AciliyetId,
                    Ad = item.Ad,
                    Durum = item.Durum,
                    Id = item.Id,
                    OlusturulmaTarih = item.OlusturulmaTarih
                };
                models.Add(model);
                

            }
            return View(models);
        }

        public IActionResult EkleGorev()
        {
            TempData["Active"] = "gorev";
            ViewBag.Aciliyetler = new SelectList(_aciliyetService.GetirHepsi(), "Id", "Tanim");
            return View(new GorevAddViewModel());
        }


        [HttpPost]
        public IActionResult EkleGorev(GorevAddViewModel model)
        {
            TempData["Active"] = "gorev";
            if (ModelState.IsValid)
            {
                _gorevService.Kaydet(new Gorev()
                {

                    Ad = model.Ad,
                    Aciklama=model.Aciklama,
                    AciliyetId=model.AciliyetId

                });
                return RedirectToAction("Index");
            }
            return View(model);
        }

    }
}

ACARProje.ToDo.Web/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ACARProje.ToDo.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ACARProje.ToDo.Web/Areas/Member/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ACARProje.ToDo.Web.Areas.Member.Controllers
{
   
    [Area("Member")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ACARProje.ToDo.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ACARProje.ToDo.Business.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace ACARProje.ToDo.Web.Controllers
{
    public class HomeController : Controller
    {
        IGorevService _gorevService;
        public HomeController(IGorevService gorevService)
        {
            _gorevService = gorevService;
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

ACARProje.ToDo.Web/Areas/Admin/Views/Aciliyet/EkleAciliyet.cshtml
@model AciliyetAddViewModel
@{
    ViewData["Title"] = "EkleAciliyet";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<form class="w-75 mx-auto p-3" method="post">

    <div class="form-group">
        <label asp-for="Tanim"></label>
        <span asp-validation-for="Tanim" class="text-danger"></span>
        <input type="text" asp-for="Tanim" class="form-control" />
    </div>
    <button class="btn btn-info btn-sm" type="submit">Kaydet</button>
</form>
@section JavaScript{
    <script src="~/lib/jqueryValidate/jquery.validate.min.js"></script>
    <script src="~/lib/jqueryUnob/jquery.validate.unobtrusive.min.js"></script>
}

ACARProje.ToDo.Web/Areas/Admin/Views/Aciliyet/GuncelleAciliyet.cshtml
@model AciliyetUpdateViewModel
@{
    ViewData["Title"] = "GuncelleAciliyet";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<form asp-action="GuncelleAciliyet" class="w-75 mx-auto p-3" method="post">

    <div class="form-group">
        <input type="hidden" asp-for="Id" />
        <label asp-for="Tanim"></label>
        <span asp-validation-for="Tanim" class="text-danger"></span>
        <input type="text" asp-for="Tanim" class="form-control" />
    </div>
    <button class="btn btn-info btn-sm" type="submit">Kaydet</button>
</form>
@section JavaScript{
    <script src="~/lib/jqueryValidate/jquery.validate.min.js"></script>
    <script src="~/lib/jqueryUnob/jquery.validate.unobtrusive.min.js"></script>
}

ACARProje.ToDo.Web/Areas/Admin/Views/Aciliyet/Index.cshtml
@model List<AciliyetListViewModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}




@if (Model.Count != 0)
{
    <a asp-action="EkleAciliyet" asp-controller="Aciliyet" class="btn btn-sm btn-info my-2"> Yeni Aciliyet Ekle</a>
    <table class="table table-hover table-sm">
        <thead>
            <tr>
                <th>Tanim</th>
                <th>İşlem</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Tanim</td>
                    <td>
                        <a asp-action="GuncelleAciliyet" asp-controller="Aciliyet" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Düzenle</a>
                    </td>
                </tr>

            }

        </tbody>
    </table>

}
else
{

    <div class="text-center lead mt-4">
        <p class="lead">
            Sistemde kayıtlı aciliyet durumu bulunamadı !
        </p>
        <a asp-action="EkleAciliyet" asp-controller="Aciliyet" class="btn btn-sm btn-info my-2"> Yeni Aciliyet Ekle</a>
    </div>
}

ACARProje.ToDo.Web/Areas/Admin/Views/Gorev/EkleGorev.cshtml
@model GorevAddViewModel
@{
    ViewData["Title"] = "EkleGorev";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<form class="w-75 mx-auto p-3" method="post">

    <div class="form-group">
        <label>Ad :</label>
        <span asp-validation-for="Ad" class="text-danger"></span>
        <input type="text" asp-for="Ad" class="form-control" />
    </div>
    <div class="form-group">
        <label>Açiklama :</label>
        <span asp-validation-for="Aciklama" class="text-danger"></span>
        <textarea asp-for="Aciklama" class="form-control">

        </textarea>
    </div>
    <div class="form-group">
        <label>Aciliyet :</label>
        <span asp-validation-for="AciliyetId" class="text-danger"></span>
        <select asp-for="AciliyetId" class="form-control" asp-items="ViewBag.Aciliyetler">
            <option hidden value="-1">Seçiniz</option>
        </select>
    </div>
    <button class="btn btn-info btn-sm" type="submit">Kaydet</button>
</form>
@section JavaScript{
    <script src="~/lib/jqueryValidate/jquery.validate.min.js"></script>
    <script src="~/lib/jqueryUnob/jquery.validate.unobtrusive.min.js"></script>
}

ACARProje.ToDo.Web/Areas/Admin/Views/Gorev/Index.cshtml
@model List<GorevListViewModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



@if (Model.Count != 0)
{
    <a asp-action="EkleGorev" asp-controller="Gorev" class="btn btn-sm btn-info my-2"> Yeni Gorev Oluştur</a>
    <table class="table table-hover table-sm">
        <thead>
            <tr>
                <th>Ad</th>
                <th>Aciklama</th>
                <th>OLuşturulma Tarihi</th>
                <th>Aciliyet</th>

                <th>İşlem</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>@item.Ad</td>
                <td>@item.Aciklama</td>
                <td>@item.OlusturulmaTarih.ToString("D")</td>
                <td>@item.Aciliyet.Tanim</td>


                <td>
                    <a asp-action="GuncelleGorev" asp-controller="Gorev" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Düzenle</a>
                    <a asp-action="SilGorev" asp-controller="Gorev" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Sil</a>

                </td>
            </tr>

            }

        </tbody>
    </table>

}
else
{

    <div class="p-3 text-center lead mt-4">
        <p class="lead">
            Herhangi bir görev bulunamadı !
        </p>
        <a asp-action="EkleGorev" asp-controller="Gorev" class="btn btn-sm btn-info my-2"> Yeni Gorev Oluştur</a>
    </div>
}

ACARProje.ToDo.Web/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Index</h1>

ACARProje.ToDo.Web/Areas/Admin/Views/Shared/_AdminLayout.cshtml
@{
    string active = string.Empty;
    if (TempData["Active"] !=null)
    {
        active = TempData["Active"].ToString();

    }
   // string active2=TempData["Active"]?.ToString();

}


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Simple Sidebar - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="~/bootswatch/bootstrap.min.css" rel="stylesheet" />

    <!-- Custom styles for this template -->

    <link href="~/lib/template-css/simple-sidebar.css" rel="stylesheet" />

</head>

<body>

    <div class="d-flex" id="wrapper">

        <!-- Sidebar -->
        <div class="border-right" id="sidebar-wrapper">
            <div class="sidebar-heading">Admin Layout </div>
            <div class="list-group list-group-flush">
                <a asp-action="Index" asp-controller="Gorev" class="list-group-item list-group-item-action @(active=="gorev"?"active":"")">Görev işlemleri</a>
                <a asp-action="Index" asp-controller="Aciliyet" class="list-group-item list-group-item-action @(active=="aciliyet"?"active":"")">Aciliyet İşlemleri</a>
                <a href="#" class="list-group-item list-group-item-action ">Overview</a>
                <a href="#" class="list-group-item list-group-item-action ">Events</a>
                <a href="#" class="list-group-item list-group-item-action ">Profile</a>
                <a href="#" class="list-group-item list-group-item-action ">Status</a>
            </div>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">

            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <button class="btn btn-primary" id="menu-toggle">Toggle Menu</button>

                @*<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                            <li class="nav-item active">
                                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Link</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Dropdown
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="#">Action</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                </div>
                            </li>
                        </ul>
                    </div>*@
            </nav>

            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- Bootstrap core JavaScript -->


    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.bundle.min.js"></script>
    @RenderSection("JavaScript",false)
    <!-- Menu Toggle Script -->
    <script>$("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });</script>

</body>

</html>

ACARProje.ToDo.Web/Areas/Member/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Member/Views/Shared/_MemberLayout.cshtml";
}

<h1>Index</h1>

ACARProje.ToDo.Web/Areas/Member/Views/Shared/_MemberLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Simple Sidebar - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="~/bootswatch/bootstrap.min.css" rel="stylesheet" />

    <!-- Custom styles for this template -->

    <link href="~/lib/template-css/simple-sidebar.css" rel="stylesheet" />

</head>

<body>

    <div class="d-flex" id="wrapper">

        <!-- Sidebar -->
        <div class="border-right" id="sidebar-wrapper">
            <div class="sidebar-heading">Member Layout </div>
            <div class="list-group list-group-flush">
                <a href="#" class="list-group-item list-group-item-action active">Görev işlemleri</a>
                <a href="#" class="list-group-item list-group-item-action ">Shortcuts</a>
                <a href="#" class="list-group-item list-group-item-action ">Overview</a>
                <a href="#" class="list-group-item list-group-item-action ">Events</a>
                <a href="#" class="list-group-item list-group-item-action ">Profile</a>
                <a href="#" class="list-group-item list-group-item-action ">Status</a>
            </div>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">

            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <button class="btn btn-primary" id="menu-toggle">Toggle Menu</button>

                @*<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                            <li class="nav-item active">
                                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Link</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Dropdown
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="#">Action</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                </div>
                            </li>
                        </ul>
                    </div>*@
            </nav>

            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- Bootstrap core JavaScript -->


    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Menu Toggle Script -->
    <script>$("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });</script>

</body>

</html>

ACARProje.ToDo.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_StandartLayout.cshtml";
}

<h1>Index</h1>
<a asp-area="Admin" asp-controller="Home" asp-action="Index">Admin sayfasına git</a>
<a asp-area="Member">Member sayfasına git</a>

ACARProje.ToDo.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Simple Sidebar - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="~/bootswatch/bootstrap.min.css" rel="stylesheet" />

    <!-- Custom styles for this template -->

    <link href="~/lib/template-css/simple-sidebar.css" rel="stylesheet" />

</head>

<body>

    <div class="d-flex" id="wrapper">

        <!-- Sidebar -->
        <div class="border-right" id="sidebar-wrapper">
            <div class="sidebar-heading">Start Bootstrap </div>
            <div class="list-group list-group-flush">
                <a href="#" class="list-group-item list-group-item-action active">Görev İşlemleri</a>
                <a href="#" class="list-group-item list-group-item-action ">Shortcuts</a>
                <a href="#" class="list-group-item list-group-item-action ">Overview</a>
                <a href="#" class="list-group-item list-group-item-action ">Events</a>
                <a href="#" class="list-group-item list-group-item-action ">Profile</a>
                <a href="#" class="list-group-item list-group-item-action ">Status</a>
            </div>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">

            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <button class="btn btn-primary" id="menu-toggle">Toggle Menu</button>

                @*<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
            </ul>
        </div>*@
            </nav>

            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- Bootstrap core JavaScript -->


    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Menu Toggle Script -->
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });</script>

</body>

</html>

ACARProje.ToDo.Web/Views/Shared/_StandartLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>